services:
  build-image:
    image: cli-embedded
    command: bash -c "echo build-image completed."
    build: .
  build-project:
    image: cli-embedded
    command: bash -c "chmod +x build.sh && ./build.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  unit-tests:
    image: cli-embedded
    command: bash -c "chmod +x unit-tests.sh && ./unit-tests.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  code-coverage:
    image: cli-embedded
    command: bash -c "ceedling version && ceedling gcov:all utils:gcov"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  static-analysis:
    image: cli-embedded
    command: bash -c "chmod +x static-analysis.sh && ./static-analysis.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app