name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build_example:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: build example
        run:  docker compose run --rm build-example

  run_tests:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: run unit tests
        run:  docker compose run --rm unit-tests
