name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run:  docker compose build
      - name: build project
        run:  docker compose run --rm build-project
      - name: run unit tests
        run:  docker compose run --rm unit-tests
