# syntax for this file https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# help on github actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    runs-on: ubuntu-latest

    container:
      image: throwtheswitch/madsciencelab

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: run unit tests
        run:  ceedling clobber && ceedling test:all
      - name: run test coverage report
        run:  ceedling gcov:all utils:gcov